version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Instalar Dependencias
          command: npm install
      - run:
          name: Executar Testes Automatizados
          command: npm test
      
      # PLUGIN DE RELATÓRIO: Salva os resultados gerados para o painel do CircleCI
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: mocha-report

workflows:
  run-pipeline:
    jobs:
      - build-and-test
