version: 2.1

jobs:
  build-and-test:
    # Ativa o uso do agente proprietário (Self-hosted runner)
    machine: true
    resource_class: milarcorreia/meu-computador
    
    steps:
      - checkout
      - run:
          name: Instalar Dependencias no Agente Local
          command: npm install
      - run:
          name: Executar Testes Automatizados no Agente
          command: npm test
          
      # Plugin de relatórios das etapas anteriores
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: mocha-report

workflows:
  run-pipeline:
    jobs:
      - build-and-test
